### ISSUE TITLE
Are the MKL shared libraries in the external directory different from the installed MKL shared libraries ?

### ISSUE THREAD

**Issue by wuzhijiexia** [intel/caffe#18]
current MKL libs --- the MKL shared libraries in the external directory
local MKL libs --- the installed MKL shared libraries

I modify the path of current MKL libs(caffe/external/...) to become the path of local MKL libs(/opt/intel/mkl/...). But when linking, many problems are found what are 'xxx is not defined'.
The current MKL lib which is linked is mkl_avx512_mic.so.
![image 1](https://cloud.githubusercontent.com/assets/19603119/20251646/caa3cda4-aa55-11e6-9ed6-b9d95b99a439.png)

**Comment by jczaja** [comment]
Caffe works when linked against MKL from external directory as well as installed MKL. The one that is
being downloaded is a special build of MKL that contains only subset of functionality provided by installed MKL . If your installed MKL is new enough it can be used for caffe eg. set your installed MKL up
for work by sourcing /opt/intel/mkl/../mklvars.sh intel64 . That way you will have MKLROOT env var set. Based on that building system of caffe will recognize that you want to use that particular MKL and if only it is not that old the one You pointed will be used (in external/mkl/prepare_mkl.sh there is VERSION_LINE var with bottom data below which pointed MKL is considered obsolete). 

You mentioned that you have modified  the path of current MKL ? What was done exactly?
As I would  suggest to just set MKLROOT to location when your MKL you want to use, is rather than any changes in caffe scripts.

Also please provide the version of your local (installed) MKL .

Regards,
Jacek

**Comment by wuzhijiexia** [comment]
Thank you very much. These help me greatly. I will try it by your suggestions.
