### ISSUE TITLE
lock in SyncedMemory::cpu_data hurts performance a lot in multithread senario

### ISSUE THREAD

**Issue by hanzz2007** [intel/caffe#216]
we are testing intel-caffe as inference engine, while found that if each thread has its own net instance, and running its own net::forward concurrently,  lock(mtx) in SyncedMemory::cpu_data  will hurts performance a lot, makes about 1x slower than single thread mode

**Comment by hanzz2007** [comment]
additional info: we tested on windows

**Comment by jgong5** [comment]
It is not supported right now. There are multiple things to do to support such a multi-threading inference configuration. Firstly, you have to submit MKL-DNN primitives from separate stream holders as you mentioned. You also have to carefully configure OpenMP properly so that multiple main threads would use separate thread resources. Finally, I'm not sure if MKL-DNN can support multiple main threads well.

**Comment by hanzz2007** [comment]
omp will not be a problem for i can disable the omp features to make each inst  running in exact one thread, and mkldnn supports multithread which i can make sure. i can even disable omp in mkldnn and replace the mklml with mkl_sequential.  So i think if i can make each net instance have its own streamholder, it will be possible to  make intel-caffe to support multithread mode

**Comment by ftian1** [comment]
@hanzz2007 just like jgong5 said, mkldnn don't support such multiple-thread feature. in fact, what we used to replace your use case is multi-instance, that's multi-process.

**Comment by hshen14** [comment]
Please try multi-instances solution.
