### ISSUE TITLE
MLSL library error

### ISSUE THREAD

**Issue by andreiuc** [intel/caffe#56]
Hello,

I am trying to run Intel's version of Caffe for benchmarking purposes, which I downloaded from:

                    http://github.com/intel/caffe.git

The  training command works fine when running on a local system (without MPI) but when trying to use MPI  like in the following command:

         mpirun -v -n 2 -ppn 1 -machinefile /home/demouser/mpd.hosts /home/demouser/intelcaffe/build/tools/caffe train   -solver /home/demouser/dogvscat/dogvscat_solver.prototxt

I receive the following error message:

  (4328): /localdisk/jenkins/mlsl-build/src/comms_ep.cpp:CommsAlloc:535: ASSERT 'ptr' FAILED: NULL pointer

Does anybody have any idea why this occurs (the source for the MLSL library is not available - just the binary blob)?

Regards,
Andrei

**Comment by itemko** [comment]
Hi Andrei,

Feel free to submit Intel MLSL questions/issues on https://github.com/01org/MLSL

Regarding to your problem:
It is a problem with the size of internal MLSL memory.
User should increase that size over MLSL_HEAP_SIZE_GB environment variable.
For example: MLSL_HEAP_SIZE_GB=64 mpirun …
The default value is 32GB for MLSL Beta. That problem will be fixed in MLSL Gold.
