### ISSUE TITLE
DockerFiles Fail to Build

### ISSUE THREAD

**Issue by cooperpellaton** [intel/caffe#86]
When attempting to build either the CPU only or GPU dockerfiles I am greeted with
 ```
fatal error: mkl_blas.h: No such file or directory
   #include <mkl_blas.h>
```
Assuming this was because the MKL install was not being bootstrapped during the install, I added the following to my dockerfile 
``` docker
# Install Intel MKL.
RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*
RUN wget http://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
RUN sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
RUN sudo sh -c 'echo deb http://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
RUN sudo apt-get update
RUN sudo apt-get install -y intel-mkl-64bit-2017.3-056
```
But I am still met with the same error.

**Comment by cooperpellaton** [comment]
I have been able to solve the MKL issue by substituting my above addition with the following, but now the build is failing due to NVCC errors.

```docker
# # Install Intel MKL.
RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*
# RUN wget http://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
# RUN sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
# RUN sudo sh -c 'echo deb http://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
# RUN sudo apt-get update
# RUN sudo apt-get install -y intel-mkl-64bit-2017.3-056
# RUN source /opt/intel/bin/compilervars.sh intel64

ENV MKL_PATH=/opt/intel
RUN apt-get update && \
  apt-get install -y man
RUN cd /tmp && \
  wget -q http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/11544/l_mkl_2017.3.196.tgz && \
  tar -xzf l_mkl_2017.3.196.tgz && cd l_mkl_2017.3.196 && \
  sed -i 's/ACCEPT_EULA=decline/ACCEPT_EULA=accept/g' silent.cfg && \
  sed -i 's/ACTIVATION_TYPE=exist_lic/ACTIVATION_TYPE=trial_lic/g' silent.cfg && \
  ./install.sh -s silent.cfg && \
  cd .. && rm -rf *
# Add to path
# ENV PATH ${MKL_PATH}/bin:${PATH}
RUN echo "${MKL_PATH}/mkl/lib/intel64" >> /etc/ld.so.conf.d/intel.conf && ldconfig && \
  echo ". /opt/intel/bin/compilervars.sh intel64" >> /etc/bash.bashrc
```

**Comment by cooperpellaton** [comment]
I can now successfully build the `cpu-ubuntu` standalone Docker image now, but still cannot successfully build the gpu image.

**Comment by ftian1** [comment]
I pull a clean intel caffe tree, go to docker dir and run "make cpu-ubuntu" successfully. I don't see any build failure. 

if I run "make gpu-standalone", I meet a build error with CUDA7.5:
===================================
[ 11%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_exp_layer.cu.o
/opt/caffe/include/caffe/data_transformer.hpp(82): error: identifier "nullptr" is undefined

1 error detected in the compilation of "/tmp/tmpxft_0000159d_00000000-16_detection_output_layer.compute_50.cpp1.ii".
CMake Error at cuda_compile_generated_detection_output_layer.cu.o.cmake:260 (message):
  Error generating file
  /opt/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_detection_output_layer.cu.o

make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_detection_output_layer.cu.o] Error 1
===================================================
This is because some of check-ins enabled c++11 support. You can fix it by modifying your standalone/gpu/Dockerfile as follows:

-RUN git clone -b ${CLONE_TAG} --depth 1 https://github.com/intel/caffe.git . && \
+RUN git clone -b ${CLONE_TAG} --depth 1 https://github.com/ftian1/caffe.git . && \

after that, the gpu caffe docker build should succeed.

The only difference between intel caffe and my fork version is I modified the cmake/Cuda.cmake to add a build flag:

   if(UNIX OR APPLE)
 -    list(APPEND CUDA_NVCC_FLAGS -Xcompiler -fPIC)
 +    list(APPEND CUDA_NVCC_FLAGS -Xcompiler -fPIC -std=c++11)
    endif()

**Comment by cooperpellaton** [comment]
@ftian1 I am currently attempting to verify your solution. 1) It would simply be much cleaner to add the following to the Dockerfile after cloning the official repository 
```sh
sed -i 's/list(APPEND CUDA_NVCC_FLAGS -Xcompiler -fPIC/list(APPEND CUDA_NVCC_FLAGS -Xcompiler -fPIC -std=c++11/g' caffe/cmake/Cuda.cmake && \
```
ie:
```docker
# Download Intel Caffe and build the project without python bindings.
RUN git clone -b master --depth 1 https://github.com/intel/caffe.git . && \
    # Modify the Cuda cmake to add C++11 support.
    sed -i 's/list(APPEND CUDA_NVCC_FLAGS -Xcompiler -fPIC/list(APPEND CUDA_NVCC_FLAGS -Xcompiler -fPIC -std=c++11/g' caffe/cmake/Cuda.cmake && \
    # for req in $(cat python/requirements.txt) pydot; do pip install $req; done && \
    mkdir build && cd build && \
    cmake -DBUILD_python=OFF -DBUILD_matlab=OFF -DBUILD_docs=OFF -DBUILD_python_layer=OFF -DUSE_OPENMP=ON -DUSE_CUDNN=1 -DUSE_MKL2017_AS_DEFAULT_ENGINE=1 -DCMAKE_BUILD_TYPE=Release .. && \
    make -j"$(nproc)"
```
 Instead of forking just for the addition of a flag. If this does work and the solution proposed in 1) does not work then 2) a PR should be made to correct this error.

**Comment by ftian1** [comment]
agree, your solution is more concise than mine. it should work as well.

**Comment by cooperpellaton** [comment]
Just built it. Can confirm that it works. Next comment will contain a PR.

**Comment by cooperpellaton** [comment]
Just put forward #91. Should fix all of the above issues.
